spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classiccar
    driver-class-name: org.postgresql.Driver
    username: ${postgres.username}
    password: ${postgres.password}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:secret.yml

